linters:
  disable-all: true
  enable:
    - vet
    - gofmt
    - misspell
    - goconst
    - golint
    - errcheck
    - gosec
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode


issues:
  exclude:
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "Potential file inclusion via variable"

  exclude-use-default: false
  exclude-rules:
    - path: node/modules/lp2p
      linters:
        - golint

linters-settings:
  goconst:
    min-occurrences: 6
