version: 2.1
orbs:
  go: gotest/tools@0.0.9


jobs:
  mod-tidy-check:
    executor: go/circleci-golang
    steps:
      - go/install-ssh
      - checkout
      - go/mod-download
      - go/mod-tidy-check

workflows:
  version: 2
  ci:
    jobs:
      - go/lint:
          golangci-lint-version: 1.17.1
          executor: go/circleci-golang
      - go/test:
          executor: go/circleci-golang
          codecov-upload: true
      - mod-tidy-check
