# Default config:
[API]
ListenAddress = "/ip4/127.0.0.1/tcp/11234/http"
#  RemoteListenAddress = ""
#  Timeout = "30s"
#
[Libp2p]
ListenAddresses = ["/ip4/0.0.0.0/tcp/12340", "/ip6/::/tcp/12340"]
# for develop
#AnnounceAddresses = ["/ip4/103.44.253.2/tcp/15460","/ip4/183.240.204.123/tcp/15460","/ip4/47.56.139.17/tcp/15460"]
# for product
#AnnounceAddresses = ["/ip4/103.44.253.2/tcp/15470","/ip4/183.240.204.123/tcp/15470","/ip4/47.56.139.17/tcp/15470"]
#
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#ConnMgrLow = 10
#ConnMgrHigh = 30
#ConnMgrGrace = "20s"
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#  PubsubTracing = false
#
